[versions]
minecraft = "26.1-snapshot-1"
minecraft-mod = "26.1-alpha.1"
fabric-loader = "0.18.3"
fabric-language-kotlin = "1.13.8+kotlin.2.3.0"
fabric-api = "0.140.1+26.1"
adventure = "4.25.0"
log4j = "2.24.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
